version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      URL: '192.168.99.101'
      COURSES_PORT: '3000'
      COURSES_ENTRY: 'courses-ms/resources/courses'
      USERS_PORT: '3003'
      USERS_ENTRY: 'api/'
    ports:
      - '5000:5000'